### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by zac-garby** [haskell-hvr/hslogger#44] opened 2017-07-23 21:52 UTC
I'm trying to install _hslogger_, using the command `cabal install hslogger-1.2.10`. However, it doesn't work -- it tells me `hlogger-1.2.10 failed during the building phase. The exception was: ExitFailure 1`.

Any idea why this is happening? I need hslogger to get MissingH.

I'm on macOS Sierra, if that's of any use.

**Comment by hvr** [comment] 2019-01-21 09:38
I can't reproduce this; I do suspect this might have been fixed in the meantime. I'm optimistically closing this, but feel free to reopen/open a new ticket if the problem persists.

**Closed by hvr** 2019-01-21 09:38 UTC
